### ISSUE TITLE
Decision Tracker - Describe the Workload Deployment Status mechanism

### ISSUE THREAD

**Issue by ajcraig** [margo/specification#10]
Below, I have outlined a proposal for the Deployment Status Update File, that is utilized by the Workload Orchestration Agent to inform the WOS of the status per deployment. 

**Note:** This proposal is one option to inform the WOS the status of the deployments. An additional option would be to utilize OTEL, but IMO I think we should have a mechanism for simple status updates and OTEL to provide further detail depending on the level of adoption the WOS intends to implement. 

The associated workflow / use case for this is detailed below:
1. Application is deployed to the Edge Device via the deployment service
2. Following the installation, the WOA creates the following Deployment status file. 
3. WOA sends northbound the status file to inform the WOS of the deployment status. 

# Proposed Margo Deployment Status Update
```apiVersion: deploymentstatus.margo/v1
kind: Margo Deployment Status
metadata:
    name: hello-world-deployment
    uniqueId: #######
deploymentInformation:
    status:
```
## Top-level Attributes

| Attribute       | Type            | Required?       | Description     |
|-----------------|-----------------|-----------------|-----------------|
| metadata        | Metadata    | Y    | Metadata element specifying characteristics about the deployment. See the [Metadata](#metadata-attributes) section below. |
| deploymentInformation        | Deployment Information    | Y    | Deployment information element describing information related to the deployment of the workload. . See the [Deployment Attributes](#deployment-information-attributes) section below. |

## Metadata Atrributes
| Attribute       | Type            | Required?       | Description     |
|-----------------|-----------------|-----------------|-----------------|
| name      | string    | Y    | Name of corresponding deployment created by the Workload Orchestration Software assigned to the device via the Device Orchestration Software.|
| uniqueID            | string    | Y    | Unique ID of the Deployment to ensure the Workload Orchestration Software can match the status with the deployment.|

## Deployment Information Attributes
| Attribute       | Type            | Required?       | Description     |
|-----------------|-----------------|-----------------|-----------------|
| status      | string    | Y    | Status attribute that includes a quick status indicator for the Workload Orchestration Software. **Note:** Still need to figure out what we want to standardize on updates in this capacity. |

**Comment by ajcraig** [comment]
@margo/technical-wg new proposal for review on deployment status file.

**Comment by phil-abb** [comment]
We probably need some additional information. What about expanding it to something like this

- `deploymentId` would match the uniqueId from the [application deployment](https://github.com/margo/specification/issues/3). I'm not sure if using `uniqueId` here makes the intent clear enough that this is the same as the id for the deployment.
- `timestamp` so the WOS can determine the message order more easily
- `state` would be an enum with options: `pending`, `installing`, `installed`, `failed`

```yaml
apiVersion: deployment.margo/v1
kind: DeploymentStatus
metadata:
    deploymentId: 
    timeStamp:
status:
  state:
  error:
    code:
    message:
  components:
    - name:
      state:
      error:
        code:
        message:
```

**Example 1**

```yaml
apiVersion: deployment.margo/v1
kind: DeploymentStatus
metadata:
    deploymentId: 3a5549f2-02a4-4faf-9bc4-1ea9866684c1
    timeStamp: 2024-06-10 08:37:54Z
status:
  state: installing
  components:
    - name: digitron-orchestrator
      state: installed
    - name: database-services
      state: installing
```

**Example 2**

```yaml
apiVersion: deployment.margo/v1
kind: DeploymentStatus
metadata:
    deploymentId: 3a5549f2-02a4-4faf-9bc4-1ea9866684c1
    timeStamp: "2024-06-10 09:03:27Z"
status:
  state: installed
  components:
    - name: digitron-orchestrator
      state: installed
    - name: database-services
      state: installed
 ```

**Example 3**

```yaml
apiVersion: deployment.margo/v1
kind: DeploymentStatus
metadata:
    deploymentId: 3a5549f2-02a4-4faf-9bc4-1ea9866684c1
    timeStamp: "2024-06-10 08:51:13Z"
status:
  state: failed
  components:
    - name: digitron-orchestrator
      state: installed
    - name: database-services
      state: failed
      error:
        code: InvalidArgument
        message: "failed to provision volume with StorageClass 'default': rpc error: code = InvalidArgument desc = unsupported access mode: MULTI_NODE_MULTI_WRITER"
```

 **Example 4**
 
 ```yaml
 apiVersion: deployment.margo/v1
kind: DeploymentStatus
metadata:
    deploymentId: 3a5549f2-02a4-4faf-9bc4-1ea9866684c1
    timeStamp: "2024-06-10 09:03:27Z"
status:
  state: failed
  error:
    code: HostUnavailable
    Error: "Unable to communicate with the Kubernetes cluster" 
  components:
    - name: digitron-orchestrator
      state: pending
    - name: database-services
      state: pending
````
 
 
 This is the workflow I have in mind for installing new applications.
 
![install sequence](https://github.com/margo/specification/assets/27506475/9953f69e-4447-4238-9fd5-708c1040723b)
