### ISSUE TITLE
New deploymentProfile: SingleContainer

### ISSUE THREAD

**Issue by jjaswanson4** [margo/specification#67]
### Description

This is a proposal, not yet completed, to add a deploymentProfile to the spec to encompass deploying a single container, optionally with additional args, to devices under the management of a manager.

For example:
```yaml
deploymentProfiles:
  - type: singleContainer
    components:
      - name: my-container
        properties:  
          image: quay.io/my-org/my-image:latest
          ports:
            - 8080:8080
          privileged: true
```

This deployment would still fall under "deployment evaluation" performed by the manager: "can the target device run this workload", and can use the existing mechanisms to be delivered to the WOAs.

This should provide the ability to pass all available options down to the container engine (docker/podman), for example: https://docs.podman.io/en/v5.1.1/markdown/podman-run.1.html#options

### Motivation

The other deploymentProfiles encompass workloads that typically involve multiple containers, and optionally, communication constructs (services, routes), as well as other constructs (configMaps, secrets, etc etc etc).

These are predicated on the workload being somewhat modernized, and broken up into smaller components that now communicate with each other, or have been "elevated" to work within a k8s/k3s environment.

Some vendors have not yet reached this level with their software development, instead having something more straightforward: tossing the installation commands into a Dockerfile, and building an image, which then provides the same functionality at the application level, yet is a valid containerized workload.

This deploymentProfile provides a bit of an on-ramp for vendors as they undergo software modernization, and there are some workloads where just a simple single container meets the running requirements.
