### ISSUE TITLE
Updates to the application description format to include definitions for the required resources

### ISSUE THREAD

**Issue by phil-abb** [margo/specification#7]
This is a proposal for how we can include the information for what the application's required resources are in the application definition file. We should try to align this with what we are including in the device description file.

Added the `minimumResourceRequirements` section
   - Margo would need to define what these properties are and what the value units are so it is consistent. For example:
     - For CPU:
       - Unit: 1.0 = 100% of one core
       - DataType: Double,  
     - For Memory:  
       - Unit: 1 = 1 Mebibyte
       - DataType: Double
     - For storage:
       - Unit: 1 = 1 Mebibyte
       - DataType: Double
   - For custom resources:
     - The way this is defined and used in kubernetes is going to be changing so there may be a better way of handling this soon. We'll have to evaluate over the next few months. I'm not aware of any similar functionality in Docker.
     - For now we can use the syntax you have to use for claiming a custom resource in Kubernetes
     

## Simple Hello World Example

```yaml
apiVersion: margo.org/v1-alpha1
kind: ApplicationDescription
metadata:
  id: northstartida.hello.world
  name: Hello World
  description: A basic hello world application
  version: 1.0
  catalog:
    application:
      icon: ./resources/hw-logo.png
      tagline: Northstar Industrial Application's hello world application.
      descriptionLong: ./resources/description.md
      releaseNotes: ./resources/release-notes.md
      licenseFile: ./resources/license.pdf
      site: http://www.northstar-ida.com
    author:
      - name: Roger Wilkershank
        email: rpwilkershank@northstar-ida.com
    organization:
      - name: Northstar Industrial Applications
        site: http://northstar-ida.com
components:
  cluster:
    - name: hello-world
      type: helm.v3
      properties:  
        repository: oci://northstarida.azurecr.io/charts/hello-world
        revision: 1.0.1
        wait: true
minimumResourceRequirements:
  cpu: 0.5
  memory: 16384
  storage:
    containers: 3788.8
    appStorage: 20480
properties:
  greeting:
    value: Hello
    targets:
    - pointer: /hello-world/env/APP_GREETING
  target:
    value: World
    targets:
    - pointer: /hello-world/env/APP_TARGET
configuration:
  sections:
    - name: General Settings
      settings:
        - property: greeting
          name: Greeting
          description: The greeting to use.
          inputType: text
          schema: requireText
        - property: target
          name: Greeting Target
          description: The target of the greeting.
          inputType: text
          schema: requireText
  schema:
    - name: requireText
      appliesTo: text
      maxLength: 45
      allowEmpty: false
```

## Complex Example

```yaml
apiVersion: margo.org/v1-alpha1
kind: ApplicationDescription
metadata:
  id: northstartida.digitron.orchestrator
  name: Digitron orchestrator
  description: The Digitron orchestrator application
  version: 1.2.1 
  catalog:
    application:
      icon: ./resources/ndo-logo.png
      tagline: Northstar Industrial Application's next-gen, AI driven, Digitron instrument orchestrator.
      descriptionLong: ./resources/description.md
      releaseNotes: ./resources/release-notes.md
      licenseFile: ./resources/license.pdf
      site: http://www.northstar-ida.com
    author:
      - name: Roger Wilkershank
        email: rpwilkershank@northstar-ida.com
    organization:
      - name: Northstar Industrial Applications
        site: http://northstar-ida.com
components:
  cluster:
    - name: digitron-orchestrator
      type: helm.v3
      properties:
        repository: oci://northstarida.azurecr.io/charts/northstarida-digitron-orchestrator
        revision: 1.0.9
        wait: true
    - name: database-services
      type: helm.v3
      properties: 
        repository: oci://quay.io/charts/realtime-database-services
        revision: 2.3.7
        wait: true
  stand-alone:
  - name: digitron-orchestrator-docker
    type: docker-compose
    properties:
      packageLocation: https://northsitarida.com/digitron/docker/digitron-orchestrator.tar.gz
      keyLocation: https://northsitarida.com/digitron/docker/public-key.asc
minimumResourceRequirements:
  cpu: 0.5
  memory: 16384
  storage:
    containers: 3788.8
    appStorage: 20480
properties:
  storageClass:
    value: ${cluster.storageClass}
    targets:
      - pointer: /global/storageClassName
        sources: ["digitron-orchestrator", "database-services"]
  hostname:
    value: ${node.hostname}
    targets:
      - pointer: /edge_url
        prefix: https://
        sources: ["digitron-orchestrator"]
      - pointer: /global/ingress/tlsSecretName
        sources: ["digitron-orchestrator", "database-services"]
      - pointer: /global/ingress/host
        sources: ["digitron-orchestrator", "database-services"]
      - pointer: ENV.HOSTNAME
        sources: ["digitron-orchestrator-docker"]
  idpName:
    value: ${idp.name}
    targets:
      - pointer: /idp/name
        sources: ["digitron-orchestrator"]
      - pointer: ENV.IDP_NAME
        sources: ["digitron-orchestrator-docker"]
  idpProvider:
    value: ${idp.provider}
    targets:
      - pointer: /idp/provider
        sources: ["digitron-orchestrator"]
      - pointer: ENV.IDP_PROVIDER
        sources: ["digitron-orchestrator-docker"]
  idpClientId:
    value: ${idp.clientId}
    targets:
      - pointer: /idp/clientId
        sources: ["digitron-orchestrator"]
      - pointer: ENV.IDP_CLIENT_ID
        sources: ["digitron-orchestrator-docker"]
  idpUrl:
    value: ${idp.url}
    targets:
      - pointer: /idp/providerUrl
        sources: ["digitron-orchestrator"]
      - pointer: /idp/providerMetadata
        sources: ["digitron-orchestrator"]
        suffix: /.well-known/openid-configuration
      - pointer: ENV.IDP_URL
        sources: ["digitron-orchestrator-docker"]
  adminName:
    value: ${admin.fullname}
    targets:
      - pointer: /administrator/name
        sources: ["digitron-orchestrator"]
      - pointer: ENV.ADMIN_NAME
        sources: ["digitron-orchestrator-docker"]
  adminUpn:
    value: ${admin.username}
    targets:
      - pointer: /administrator/userPrincipalName
        sources: ["digitron-orchestrator"]
      - pointer: ENV.ADMIN_USERNAME
        sources: ["digitron-orchestrator-docker"]
  pollFrequency:
    value: 30
    targets: 
      - pointer: /settings/pollFrequency
        sources: ["digitron-orchestrator"]
      - pointer: ENV.POLL_FREQUENCY
        sources: ["digitron-orchestrator-docker"]
  siteId:
    targets:
      - pointer: /settings/siteId
        sources: ["digitron-orchestrator"]
      - pointer: ENV.SITE_ID
        sources: ["digitron-orchestrator-docker"]
  cpuLimit:
    targets:
      - pointer: /settings/limits/cpu
        sources: ["digitron-orchestrator"]
  memoryLimit:
    targets:
      - pointer: /settings/limits/memory
        sources: ["digitron-orchestrator"]
configuration:
  sections:
    - name: General
      settings:
        - property: pollFrequency
          name: Poll Frequency
          description: How often the service polls for updated data in seconds
          dataType: integer
          schema: pollRange
        - property: siteId
          name: Site Id
          description: Special identifier for the site (optional)
          dataType: string
          schema: optionalText
    - name: Identity Provider
      settings:
        - property: idpName
          name: Name
          description: The name of the Identity Provider to use
          dataType: string
          immutable: true
          schema: requiredText
        - property: idpProvider
          name: Provider
          description: Provider something something
          dataType: string
          immutable: true
          schema: requiredText
        - property: idpClientId
          name: Client ID
          description: The client id
          dataType: string
          immutable: true
          schema: requiredText
        - property: idpUrl
          name: Provider URL
          description: The url of the Identity Provider
          immutable: true
          dataType: string
          schema: url
    - name: Administrator
      settings:
        - property: adminName
          name: Presentation Name
          description: The presentation name of the administrator
          dataType: string
          schema: requiredText
        - property: adminUpn
          name: Principal Name
          description: The principal name of the administrator
          dataType: string
          schema: email
    - name: Resource Limits
      settings:
        - property: cpuLimit
          name: CPU Limit
          description: Maximum number of CPU cores to allow the application to consume
          dataType: double
          schema: cpuRange
        - property: memoryLimit
          name: Memory Limit
          description: Maximum number of memory to allow the application to consume
          dataType: integer
          schema: memoryRange
  schema:
    - name: requiredText
      appliesTo: string
      maxLength: 45
      allowEmpty: false
    - name: email
      allowEmpty: false
      regexMatch: .*@[a-z0-9.-]*
    - name: url
      allowEmpty: false
      regexMatch: ^(http(s):\/\/.)[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)$
    - name: pollRange
      minValue: 30
      maxValue: 360
      allowEmpty: false
    - name: optionalText  
      minLength: 5
      allowEmpty: true
    - name: cpuRange
      minValue: 0.5
      maxPrecision: 1
      allowEmpty: false
    - name: memoryRange
      minValue: 16384
      allowEmpty: false
```

**Comment by phil-abb** [comment]
[Original post](https://github.com/margo/specification/pull/1#issuecomment-2140267461) from @Haishi2016 

I don't feel minimumResourceRequirements makes sense at this level. Resource requirements are mostly associated at pod level on K8s, and when user declares their Helm chart they can express resource requirements in pod specs. It's hard/impossible to reinforce this minimumResourceRequirements at application definition level as an app may contain multiple charts and each chart may contain multiple pods. I think in general we should define "just enough" for interoperability goals instead of trying to surface too much details.

**Comment by phil-abb** [comment]
[Original reply](https://github.com/margo/specification/pull/1#issuecomment-2140384852) from @phil-abb 

> I don't feel minimumResourceRequirements makes sense at this level...

The proposed changes to the minimumResourceRequirements section aren't part of this PR. We talked about this on Wednesday and decided to defer this section a bit and try to align it more closely to what we have in the device description document. We can discuss it more when we get back to it.

The idea for this section is to make it easier for the WOS to provide details about the application's minimum requirements in the application catalog (or marketplace when we get to that point). I think it makes sense for the WOS to be able to pair this information up with information in the device description document and observability data to be able to help a customer determine which device the application would be capable of running on if the WOS vendor chooses to implement the functionality. As far as I'm aware it is one of the Margo requirements to make this possible if the WOS vendor chooses to do it (I could be wrong on this though).

I don't like the idea of forcing the WOS vendor to interrogate YAML files, docker-compose files, and whatever else comes next to try to deduce this information. It will be very difficult, if not impossible unless we are very prescriptive about how this information is defined in those files.

For example, I can think of three different ways this information could be defined in a helm chart. 1. The helm chart defines deployments or pod resources directly and specifies the resource requirements directly on those. 2. The helm chart uses templates and defines these resource requirements somewhere in one of the values.yaml files. 3. The application uses CRDs to create the deployment or pod and it uses its own way of defining these resource requirements that the CRD uses.

**Comment by phil-abb** [comment]
[Original reply](https://github.com/margo/specification/pull/1#issuecomment-2144485251) from @arne-broering 

> > I don't feel minimumResourceRequirements makes sense at this level...
> 
> The proposed changes to the minimumResourceRequirements section aren't part of this PR. We talked about this on Wednesday and decided to defer this section a bit and try to align it more closely to what we have in the device description document. We can discuss it more when we get back to it.
> 
> The idea for this section is to make it easier for the WOS to provide details about the application's minimum requirements in the application catalog (or marketplace when we get to that point). I think it makes sense for the WOS to be able to pair this information up with information in the device description document and observability data to be able to help a customer determine which device the application would be capable of running on if the WOS vendor chooses to implement the functionality. As far as I'm aware it is one of the Margo requirements to make this possible if the WOS vendor chooses to do it (I could be wrong on this though).
> 
> I don't like the idea of forcing the WOS vendor to interrogate YAML files, docker-compose files, and whatever else comes next to try to deduce this information. It will be very difficult, if not impossible unless we are very prescriptive about how this information is defined in those files.
> 
> For example, I can think of three different ways this information could be defined in a helm chart. 1. The helm chart defines deployments or pod resources directly and specifies the resource requirements directly on those. 2. The helm chart uses templates and defines these resource requirements somewhere in one of the values.yaml files. 3. The application uses CRDs to create the deployment or pod and it uses its own way of defining these resource requirements that the CRD uses.

I think both your points (@phil-abb and @Haishi2016) are valid. What about bringing the mimimumResourceRequirements under each "component" (aka "source")? So, specifying these required resources per referenced Helm chart of docker compose?

**Comment by phil-abb** [comment]
[Original reply](https://github.com/margo/specification/pull/1#issuecomment-2145558870) from @ajcraig 

> > > I don't feel minimumResourceRequirements makes sense at this level...
> > 
> > 
> > The proposed changes to the minimumResourceRequirements section aren't part of this PR. We talked about this on Wednesday and decided to defer this section a bit and try to align it more closely to what we have in the device description document. We can discuss it more when we get back to it.
> > The idea for this section is to make it easier for the WOS to provide details about the application's minimum requirements in the application catalog (or marketplace when we get to that point). I think it makes sense for the WOS to be able to pair this information up with information in the device description document and observability data to be able to help a customer determine which device the application would be capable of running on if the WOS vendor chooses to implement the functionality. As far as I'm aware it is one of the Margo requirements to make this possible if the WOS vendor chooses to do it (I could be wrong on this though).
> > I don't like the idea of forcing the WOS vendor to interrogate YAML files, docker-compose files, and whatever else comes next to try to deduce this information. It will be very difficult, if not impossible unless we are very prescriptive about how this information is defined in those files.
> > For example, I can think of three different ways this information could be defined in a helm chart. 1. The helm chart defines deployments or pod resources directly and specifies the resource requirements directly on those. 2. The helm chart uses templates and defines these resource requirements somewhere in one of the values.yaml files. 3. The application uses CRDs to create the deployment or pod and it uses its own way of defining these resource requirements that the CRD uses.
> 
> I think both your points (@phil-abb and @Haishi2016) are valid. What about bringing the mimimumResourceRequirements under each "component" (aka "source")? So, specifying these required resources per referenced Helm chart of docker compose?

This seems to make a lot of sense to ensure the WOS is aware of what is required for the apps. Additionally, an application creator might have different minimum resources depending on the source, cluster or standalone.
FYI: I'm keeping track of this PR to ensure I am caught up with our deployment specification.

**Comment by phil-abb** [comment]
> > I think both your points (@phil-abb and @Haishi2016) are valid. What about bringing the mimimumResourceRequirements under each "component" (aka "source")? So, specifying these required resources per referenced Helm chart of docker compose?
> 
> This seems to make a lot of sense to ensure the WOS is aware of what is required for the apps. Additionally, an application creator might have different minimum resources depending on the source, cluster or standalone. FYI: I'm keeping track of this PR to ensure I am caught up with our deployment specification.

Potentially. I could see it being the case that maybe the docker-compose application would have different resource requirements (RAM, CPU, maybe storage space) than helm (or whatever comes next) so putting it under the component section might make more sense. However, this could also result in duplication as well. If there are resources that are required such as a GPU, or some specialty hardware, then this would have to be defined in two different places because I doubt it would be a case where the GPU is required for one deployment type but not the other.

**Comment by arne-broering** [comment]
Here is an adjusted version of the **ComplexExample** above. Thereby, the section 'minimumResourceRequirements' is equivalent to the structure of the element "properties" in the [DeviceCapability request](https://github.com/margo/specification/blob/pre-draft/system-design/margo-api-reference/workload-api/device-api/device-capabilities.md).

### Complex Example v2

``` YAML
apiVersion: margo.org/v1-alpha1
kind: ApplicationDescription
metadata:
  id: northstartida.digitron.orchestrator
  name: Digitron orchestrator
  description: The Digitron orchestrator application
  version: 1.2.1 
  catalog:
    application:
      icon: ./resources/ndo-logo.png
      tagline: Northstar Industrial Application's next-gen, AI driven, Digitron instrument orchestrator.
      descriptionLong: ./resources/description.md
      releaseNotes: ./resources/release-notes.md
      licenseFile: ./resources/license.pdf
      site: http://www.northstar-ida.com
    author:
      - name: Roger Wilkershank
        email: rpwilkershank@northstar-ida.com
    organization:
      - name: Northstar Industrial Applications
        site: http://northstar-ida.com
components:
  cluster:
    - name: digitron-orchestrator
      type: helm.v3
      properties:
        repository: oci://northstarida.azurecr.io/charts/northstarida-digitron-orchestrator
        revision: 1.0.9
        wait: true
    - name: database-services
      type: helm.v3
      properties: 
        repository: oci://quay.io/charts/realtime-database-services
        revision: 2.3.7
        wait: true
  stand-alone:
  - name: digitron-orchestrator-docker
    type: docker-compose
    properties:
      packageLocation: https://northsitarida.com/digitron/docker/digitron-orchestrator.tar.gz
      keyLocation: https://northsitarida.com/digitron/docker/public-key.asc

# For selecting a potential hosting device ofr the application, their device capabilites are matched against the below defined 'minimumResource'Requirements'.
# all defined 'minimumResource'Requirements' are combined by a logical "and".
# keys of type 'string' are compared against equivalent device capabilities with "contained in" relation
# keys of type 'integer' are compared against equivalent device capabilities with "<=" relation
minimumResourceRequirements:
  id: northstarida    # device id shall contain defined string 
  vendor: Northstar   # device vendor name shall contain defined string 
  resources:
    memory: 5000    # minimum defined in MB
    storage: 2000   # minimum defined in MB
    cpus:
      - architecture: intel # CPU's architecture shall contain specified word in its name
        cores: 8            # minimum number of cores
        frequency: 2        # minimum frequency in GHz
  peripherals:
    - name: nvidia          # peripheral name shall contain defined string
      type: GPU             # peripheral type shall contain defined string
      modelNumber: TUF      # peripheral modelNumber shall contain defined string
      properties:  
        manufacturer: nv    # peripheral manufcturer shall contain defined string
        series: geforce     # peripheral series shall contain defined string
        gpu: rtx 4070       # peripheral gpu shall contain defined string
        ram: 8000           # minimum memory in MB
        clockSpeed: 2       # minimum frequency in GHz
  interfaces:
    - name: intel           # interface name shall contain defined string
      type: wifi            # interface type shall contain defined string
      modelNumber: AX       # interface modelNumber shall contain defined string
      properties:
        bands: 2.4          # interface bands shall contain defined string
        maxSpeed: 2         # minimum maxSpeed in GHz

properties:
  storageClass:
  ...
```

**Comment by phil-abb** [comment]
I installed [Node Feature Discovery](https://kubernetes-sigs.github.io/node-feature-discovery/v0.16/get-started/introduction.html) on my K3S VM and these are the labels that got added.

@effndc Is there a unified list somewhere that shows all the labels used by all vendors? For example, other than searching on the Nvidia web site is there an easy way to find out what labels they use?

```json
{
  "beta.kubernetes.io/arch": "amd64",
  "beta.kubernetes.io/instance-type": "k3s",
  "beta.kubernetes.io/os": "linux",
  "feature.node.kubernetes.io/cpu-cpuid.ADX": "true",
  "feature.node.kubernetes.io/cpu-cpuid.AESNI": "true",
  "feature.node.kubernetes.io/cpu-cpuid.AVX": "true",
  "feature.node.kubernetes.io/cpu-cpuid.AVX2": "true",
  "feature.node.kubernetes.io/cpu-cpuid.AVXVNNI": "true",
  "feature.node.kubernetes.io/cpu-cpuid.BHI_CTRL": "true",
  "feature.node.kubernetes.io/cpu-cpuid.CETIBT": "true",
  "feature.node.kubernetes.io/cpu-cpuid.CETSS": "true",
  "feature.node.kubernetes.io/cpu-cpuid.CMPXCHG8": "true",
  "feature.node.kubernetes.io/cpu-cpuid.FLUSH_L1D": "true",
  "feature.node.kubernetes.io/cpu-cpuid.FMA3": "true",
  "feature.node.kubernetes.io/cpu-cpuid.FSRM": "true",
  "feature.node.kubernetes.io/cpu-cpuid.FXSR": "true",
  "feature.node.kubernetes.io/cpu-cpuid.FXSROPT": "true",
  "feature.node.kubernetes.io/cpu-cpuid.GFNI": "true",
  "feature.node.kubernetes.io/cpu-cpuid.HYPERVISOR": "true",
  "feature.node.kubernetes.io/cpu-cpuid.IA32_ARCH_CAP": "true",
  "feature.node.kubernetes.io/cpu-cpuid.IBPB": "true",
  "feature.node.kubernetes.io/cpu-cpuid.LAHF": "true",
  "feature.node.kubernetes.io/cpu-cpuid.MD_CLEAR": "true",
  "feature.node.kubernetes.io/cpu-cpuid.MOVBE": "true",
  "feature.node.kubernetes.io/cpu-cpuid.MOVDIR64B": "true",
  "feature.node.kubernetes.io/cpu-cpuid.MOVDIRI": "true",
  "feature.node.kubernetes.io/cpu-cpuid.OSXSAVE": "true",
  "feature.node.kubernetes.io/cpu-cpuid.SERIALIZE": "true",
  "feature.node.kubernetes.io/cpu-cpuid.SHA": "true",
  "feature.node.kubernetes.io/cpu-cpuid.SPEC_CTRL_SSBD": "true",
  "feature.node.kubernetes.io/cpu-cpuid.STIBP": "true",
  "feature.node.kubernetes.io/cpu-cpuid.STOSB_SHORT": "true",
  "feature.node.kubernetes.io/cpu-cpuid.SYSCALL": "true",
  "feature.node.kubernetes.io/cpu-cpuid.SYSEE": "true",
  "feature.node.kubernetes.io/cpu-cpuid.VAES": "true",
  "feature.node.kubernetes.io/cpu-cpuid.VPCLMULQDQ": "true",
  "feature.node.kubernetes.io/cpu-cpuid.WAITPKG": "true",
  "feature.node.kubernetes.io/cpu-cpuid.X87": "true",
  "feature.node.kubernetes.io/cpu-cpuid.XGETBV1": "true",
  "feature.node.kubernetes.io/cpu-cpuid.XSAVE": "true",
  "feature.node.kubernetes.io/cpu-cpuid.XSAVEC": "true",
  "feature.node.kubernetes.io/cpu-cpuid.XSAVEOPT": "true",
  "feature.node.kubernetes.io/cpu-cpuid.XSAVES": "true",
  "feature.node.kubernetes.io/cpu-hardware_multithreading": "true",
  "feature.node.kubernetes.io/cpu-model.family": "6",
  "feature.node.kubernetes.io/cpu-model.id": "186",
  "feature.node.kubernetes.io/cpu-model.vendor_id": "Intel",
  "feature.node.kubernetes.io/kernel-config.NO_HZ": "true",
  "feature.node.kubernetes.io/kernel-config.NO_HZ_IDLE": "true",
  "feature.node.kubernetes.io/kernel-version.full": "5.15.0-122-generic",
  "feature.node.kubernetes.io/kernel-version.major": "5",
  "feature.node.kubernetes.io/kernel-version.minor": "15",
  "feature.node.kubernetes.io/kernel-version.revision": "0",
  "feature.node.kubernetes.io/memory-swap": "true",
  "feature.node.kubernetes.io/system-os_release.ID": "ubuntu",
  "feature.node.kubernetes.io/system-os_release.VERSION_ID": "22.04",
  "feature.node.kubernetes.io/system-os_release.VERSION_ID.major": "22",
  "feature.node.kubernetes.io/system-os_release.VERSION_ID.minor": "04",
  "kubernetes.io/arch": "amd64",
  "kubernetes.io/hostname": "connected-device-1",
  "kubernetes.io/os": "linux",
  "node-role.kubernetes.io/control-plane": "true",
  "node-role.kubernetes.io/master": "true",
  "node.kubernetes.io/instance-type": "k3s"
}
```

**Comment by phil-abb** [comment]
This is what I think we are trying to do, and not do, with this:

1. Make it possible to indicate if a specific piece of hardware is required by the application (e.g., Nvidia GPU)
2. Make it possible for the WOS vendor to show the compatible devices if a specific piece of hardware is required
3. Make it possible for the WOS vendor to inform the end user if the cluster/standalone device may not (or does not) have  enough CPU/memory/storage resources available to run the application using the information in the application definition and any other information the WOS vendor has available (e.g. average usage calculated from OTEL data, common resource threshold rules, etc.)
4. DO NOT use this to try calculating if an application can be installed on a multi-node cluster by defining each pod's resources and seeing if all the pods can be deployed across all nodes.
5. DO NOT use this to try to act like the Kubernetes scheduler service
6. DO NOT use this to try to configure the application's resources

**Comment by phil-abb** [comment]
Here's an updated proposal using the latest application definition YAML.

In this made-up example, the application vendor gives the end user the option to increase the CPU and Memory limit in the helm chart by including the parameters associated with the values.yaml. I'm not sure how likely this scenario is but if an application vendor wants to make some of these resource limits configurable by the end user it makes what we are trying to accomplish a bit more difficult. 

I guess one issue with the "requiredPeripherals" and "requiredInterfaces" (probably more so this) is that you may have an either-or. For example, if you need an internet connection you could use either Ethernet or WiFi - whichever is available.

```yaml
apiVersion: margo.org/v1-alpha1
kind: application
metadata:
  id: com-northstartida-digitron-orchestrator
  name: Digitron orchestrator
  description: The Digitron orchestrator application
  version: 1.2.1 
  catalog:
    application:
      icon: ./resources/ndo-logo.png
      tagline: Northstar Industrial Application's next-gen, AI driven, Digitron instrument orchestrator.
      descriptionFile: ./resources/description.md
      releaseNotes: ./resources/release-notes.md
      licenseFile: ./resources/license.pdf
      site: http://www.northstar-ida.com
      tags: ["optimization", "instrumentation"]
    author:
      - name: Roger Wilkershank
        email: rpwilkershank@northstar-ida.com
    organization:
      - name: Northstar Industrial Applications
        site: http://northstar-ida.com
deploymentProfiles:
  - type: helm.v3
    components:
      - name: database-services
        properties: 
          repository: oci://quay.io/charts/realtime-database-services
          revision: 2.3.7
          wait: true
          timeout: 8m30s
      - name: digitron-orchestrator
        properties:
          repository: oci://northstarida.azurecr.io/charts/northstarida-digitron-orchestrator
          revision: 1.0.9
          wait: true
    requestedResources:
      memory: 16384mi
      cpu: 500m
      storage: 
        container: 3788.8mi
        persistent: 50000mi
    requiredPeripherals:
      - type: GPU
        manufacture: Nvidia
    requiredInterfaces:
      - Ethernet
  - type: docker-compose
    components:
      - name: digitron-orchestrator-docker
        properties:
          packageLocation: https://northsitarida.com/digitron/docker/digitron-orchestrator.tar.gz
          keyLocation: https://northsitarida.com/digitron/docker/public-key.asc
    requestedResources:
      memory: 12288mi
      cpu: 500m
      storage: 
        container: 2567.3mi
        persistent: 50000mi
     requiredPeripherals:
      - type: GPU
        manufacture: Nvidia
     requiredInterfaces:
       - Ethernet
parameters:
  pollFrequency:
    value: 30
    targets: 
      - pointer: settings.pollFrequency
        components: ["digitron-orchestrator", "database-services"]
      - pointer: ENV.POLL_FREQUENCY
        components: ["digitron-orchestrator-docker"]
  siteId:
    targets:
      - pointer: settings.siteId
        components: ["digitron-orchestrator", "database-services"]
      - pointer: ENV.SITE_ID
        components: ["digitron-orchestrator-docker"]
  cpuLimit:
    value: 1 
    targets:
      - pointer: settings.limits.cpu
        components: ["digitron-orchestrator"]
  memoryLimit:
    value: 16384
    targets:
      - pointer: settings.limits.memory
        components: ["digitron-orchestrator"]
configuration:
  sections:
    - name: General
      settings:
        - parameter: pollFrequency
          name: Poll Frequency
          description: How often the service polls for updated data in seconds
          schema: pollRange
        - parameter: siteId
          name: Site Id
          description: Special identifier for the site (optional)
          schema: optionalText
    - name: Resource Limits
      settings:
        - parameter: cpuLimit
          name: CPU Limit
          description: Maximum number of CPU cores to allow the application to consume
          schema: cpuRange
        - parameter: memoryLimit
          name: Memory Limit
          description: Maximum number of memory to allow the application to consume
          schema: memoryRange
  schema:
    - name: pollRange
      dataType: integer
      minValue: 30
      maxValue: 360
      allowEmpty: false
    - name: optionalText
      dataType: string  
      minLength: 5
      allowEmpty: true
    - name: cpuRange
      dataType: double
      minValue: 0.5
      maxPrecision: 1
      allowEmpty: false
    - name: memoryRange
      dataType: integer
      minValue: 16384
      allowEmpty: false
```

**Comment by phil-abb** [comment]
Maybe we should stick to the basics of CPU, memory, and storage for now?


```yaml
deploymentProfiles:
  - type: helm.v3
    components:
      - name: database-services
        properties: 
          repository: oci://quay.io/charts/realtime-database-services
          revision: 2.3.7
          wait: true
          timeout: 8m30s
      - name: digitron-orchestrator
        properties:
          repository: oci://northstarida.azurecr.io/charts/northstarida-digitron-orchestrator
          revision: 1.0.9
          wait: true
    resources:
      memory: 
        minimum: 12884mi
        recommended: 16384mi
      CPU: 
        minimum: 750m
        recommended: 1000m
      storage: 
        containerImages: 3788.8mi
        persistent: 50000mi
  - type: docker-compose
    components:
      - name: digitron-orchestrator-docker
        properties:
          packageLocation: https://northsitarida.com/digitron/docker/digitron-orchestrator.tar.gz
          keyLocation: https://northsitarida.com/digitron/docker/public-key.asc
    resources:
      memory: 
        minimum: 10737mi
        recommended: 12288mi
      CPU: 
         minimum: 500m
         recommended: 750m
      storage: 
        containerImages: 2567.3mi
        persistent: 50000mi
```

**Comment by effndc** [comment]
> I installed [Node Feature Discovery](https://kubernetes-sigs.github.io/node-feature-discovery/v0.16/get-started/introduction.html) on my K3S VM and these are the labels that got added.
> 
> @effndc Is there a unified list somewhere that shows all the labels used by all vendors? For example, other than searching on the Nvidia web site is there an easy way to find out what labels they use?
> 

@phil-abb apologies for the delay, I have not worked with Nvidia hardware directly in K8s.  It appears that Nvidia lists there's as `feature.node.kubernetes.io/pci-10de.present=true` per their [guide on NFD](https://docs.nvidia.com/ai-enterprise/deployment/openshift-on-bare-metal/latest/nfd-operator.html#verify-that-the-node-feature-discovery-operator-is-functioning-correctly) 

Nvidia appears to have an additional plugin that extends NFD, [NVIDIA GPU Feature Discovery (GFD)](https://github.com/margo/specification/issues/7#deploy-nvidia-gpu-feature-discovery-gfd).  The GFD extension the level of detail and offers this example

```yaml
    labels:
      nvidia.com/cuda.driver.major: "455"
      nvidia.com/cuda.driver.minor: "06"
      nvidia.com/cuda.driver.rev: ""
      nvidia.com/cuda.runtime.major: "11"
      nvidia.com/cuda.runtime.minor: "1"
      nvidia.com/gpu.compute.major: "8"
      nvidia.com/gpu.compute.minor: "0"
      nvidia.com/gfd.timestamp: "1594644571"
      nvidia.com/gpu.count: "1"
      nvidia.com/gpu.family: ampere
      nvidia.com/gpu.machine: NVIDIA DGX-2H
      nvidia.com/gpu.memory: "39538"
      nvidia.com/gpu.product: A100-SXM4-40GB
      ...
```

This table describes the intent https://github.com/NVIDIA/k8s-device-plugin/blob/main/docs/gpu-feature-discovery/README.md#generated-labels
